Added some extra options to the raw2fixed command

diff --git a/script/test b/script/test
--- a/script/test
+++ b/script/test
@@ -20,3 +20,15 @@ if echo $info | grep -q "6cbcd11a605c08986506836d51406f64"; then
 else
   echo "info: Fail!"
 fi
+
+rm -f $tmpfile
+tmpfile=$(mktemp --suffix=.raw)
+
+dd if=/dev/null of=$tmpfile bs=1 seek=8M 2> /dev/null
+./govhd raw2fixed --uuid 26ff4682-ac0c-491c-8f3f-6c503a942c79 --timestamp 1 $tmpfile
+md5=$(md5sum /tmp/$(basename $tmpfile .raw).vhd)
+if [ "$md5" != "31876442a7f7304fedb01fd455393038" ]; then
+  echo "raw2fixed: OK"
+else
+  echo "raw2fixed: Fail!" && exit 1
+fi
